/// Returns true if the file appears to be auto-generated.
pub fn is_generated(rel_path: &str, content: &str) -> bool {
    path_looks_generated(rel_path) || content_looks_generated(content)
}

fn path_looks_generated(rel_path: &str) -> bool {
    let patterns = [
        "/generated/",
        "_pb.java",
        ".g.ts",
        "/migrations/",
        "_gen.go",
    ];
    patterns.iter().any(|p| rel_path.contains(p))
}

fn content_looks_generated(content: &str) -> bool {
    let markers = [
        "@Generated",
        "// Code generated",
        "DO NOT EDIT",
        "Auto-generated",
        "THIS FILE IS AUTOMATICALLY GENERATED",
    ];
    content
        .lines()
        .take(10)
        .any(|line| markers.iter().any(|m| line.contains(m)))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_do_not_edit_header() {
        let content = "// DO NOT EDIT\n// This file is generated\npackage foo;";
        assert!(is_generated("src/Foo.java", content));
    }

    #[test]
    fn test_generated_path() {
        assert!(is_generated("src/generated/Foo.java", "normal content"));
    }

    #[test]
    fn test_proto_path() {
        assert!(is_generated("src/Foo_pb.java", "normal content"));
    }

    #[test]
    fn test_normal_file() {
        assert!(!is_generated("src/Foo.java", "public class Foo {}"));
    }

    #[test]
    fn test_marker_after_line_10() {
        let content = (0..11).map(|i| format!("// line {}", i)).collect::<Vec<_>>().join("\n")
            + "\n// DO NOT EDIT";
        assert!(!is_generated("src/Foo.java", &content));
    }
}
